name: Atualização BC Secundário

on:
  schedule:
    - cron: "0 5 * * 2-6"
  workflow_dispatch: null

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
    
      - name: Install dependencies
        run: pip install -r requirements.txt
    
      - name: Run update script
        run: python update_bc_sec.py

      - name: Commit and push changes
        run: |
          git config --local user.email "cr.cj@outlook.com"
          git config --local user.name "Carlos Carvalho"
          git add bc_secundario.parquet
          git commit -m "BC Secundário atualizado em [$(date +'%Y-%m-%d')]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
